### ISSUE TITLE
Google plus share link not working

### ISSUE THREAD

**Issue by msonowal** [prodeveloper/social-share#12]
When I click on google plus share link it just opens a popup of the link but does not show or share dialogue related to google plus

**Comment by datashaman** [comment]
If I create a share URL for gplus to example.com, this is generated (https://plus.google.com/share?url=http%3A%2F%2Fexample.com)

When I click on the link I am taken to this:
![share on google](https://cloud.githubusercontent.com/assets/59514/19835142/dd4c17da-9e85-11e6-9714-d57861026482.png)

Google Plus reads the description of the page from its index or the metadata on the page, you cannot override it.
