### ISSUE TITLE
Class 'Share' not found

### ISSUE THREAD

**Issue by UXandre** [prodeveloper/social-share#16]
Hi, 

This works perfectly on my localserver but the class somehow can't be found on the remote server. I checked the log file and it says:

local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Share' not found in /var/www/laravel/app/Http/Controllers/BlogController.php:24

I however have added this line to my BlogController.php:
use Share;

**Service provider:**
Chencha\Share\ShareServiceProvider::class,

**Alias**:
'Share' => Chencha\Share\ShareFacade::class,

I've been googling for whole day long but couldn't really sort it out. There are quite a few people referring the capitalisation issue. Have given it a try but had no luck. Could you please help me out?

That would be really appreicated.

**Comment by datashaman** [comment]
Can you post your code for me to see?

**Comment by UXandre** [comment]
Hi,

Thanks a lot for willing to help. This is the repository I just pushed my files to:
https://github.com/FavourUp/blogstyle-editorial

The domain with the live server is at: https://UXandre.com

I'm looking forward to hearing back from you soon.

**Comment by UXandre** [comment]
In order to give you a quick glimpse of my codes in the BlogController.php file:


namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Post;
use App\Comments;
use Share;

class BlogController extends Controller
{
	public function getIndex(){
		$posts = Post::paginate(10);
		return view('blog.index')->withPosts($posts);
	}

    public function getSingle($slug){

    	$post = Post::where('slug', '=', $slug)->first();
		$posturl = url("blog/$slug");
		$sharelinks = Share::load($posturl, $post->title)->services('facebook','twitter','email','pinterest');
    	return view('blog.single')->withPost($post)->withSharelinks($sharelinks);
    }
}

//-----------------------------------------------


Hope this helps!

**Comment by UXandre** [comment]
Hi datashaman, 

I've figured out the issue with a friend of mine. It's not anything regarding the codes themselves. It's an issue on server. I was with a VPS provider, Vultr.com. Due to the issue happening, I moved to _DigtialOcean_, and everything works just fine now. Thank you very much for your time!

Last but not least, the package is awesome!

**Comment by datashaman** [comment]
Good to hear you got it sorted! Thanks for getting back to me. :)
