### ISSUE TITLE
Please support Telegram and WeChat

### ISSUE THREAD

**Issue by DesmondPang** [prodeveloper/social-share#17]
Please support Telegram and WeChat. Thanks

**Comment by datashaman** [comment]
@DesmondPang thanks for the request, I've added Telegram.me share support, but I can't find any good docs for WeChat. If you can point me to the correct docs, I'll be happy to add that as well.

**Comment by DesmondPang** [comment]
I found that WeChat has not official document about URL scheme. It forces developers to use its SDK to make it. Some developers reverse its private URL scheme but it is not stable and limits to some app versions. Therefore, forget it. Thanks

**Comment by datashaman** [comment]
Ok, great. I'll close and release with the new provider.
