### ISSUE TITLE
how to use it in blade template.

### ISSUE THREAD

**Issue by price2b** [prodeveloper/social-share#19]
I used the example in the controller and is not giving me any error: `return view('static.index')->withSharelinks($sharelinks);`

On the other hand I dont know the way I have to use the information in blade template. My idea is to pass the array:

```
{
    "gplus" : "https://plus.google.com/share?url=http%3A%2F%2Fwww.example.com",
    "twitter" : "https://twitter.com/intent/tweet?url=http%3A%2F%2Fwww.example.com&text=Link+description",
    "facebook" : "https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.example.com&title=Link+description"
}
```
, any help appreciated.

**Comment by kevinruscoe** [comment]
the `-> withSharelinks($sharelinks)` should create a variable called `$sharelinks` with the contents of `$sharelinks`. So just echo `$sharelinks['gplus'] `.

I'd actually change the sample to 

    return view('static.index', [
        'sharelinks' => $sharelinks
    ]);

then `$sharelinks['gplus']` should work as well.

**Comment by price2b** [comment]
excellent kevin. thank you so much!.
