### ISSUE TITLE
How do i pass a thumbnail image with every services?

### ISSUE THREAD

**Issue by Varun006** [prodeveloper/social-share#22]
Hello,

Is there  a way which allows to share a thumbnail with each of the services?

**Comment by datashaman** [comment]
No, services generally scrape the website that is referenced to get an image.

Add a prominent image to the content you are sharing and/or use OG tags to annotate your pages (specifically `og:image`), and you will see good results.

https://developers.facebook.com/docs/sharing/webmasters

**Comment by Varun006** [comment]
Thank you for the reply.

But the meta-tags did not help, also after I share the post on facebook
redirects to the URL : https://www.facebook.com/dialog/return/close?#_=_


How can i redirect the user back to my website?  





On Thu, Apr 27, 2017 1:00 PM, datashaman notifications@github.com  wrote:
Closed #22.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.




--Varun Davda
PHP Developer

**Comment by datashaman** [comment]
When posting the link to the share, add an attribute `target="_blank"` to the `a` link, something like this:

    <a href="https://www.facebook.com/........." target="_blank">Facebook</a>

When the user clicks on the link, it will open in a new window.

Alternately I think you can setup a Facebook app and configure the app to redirect that way, but I don't have experience with this.
