### ISSUE TITLE
Share an image with Twitter

### ISSUE THREAD

**Issue by dealeo** [prodeveloper/social-share#23]
Hi,
Can you please tell me if this is possible to add some code to share an image with twitter?

I already tried to change code in social-share.php file with these examples :
'twitter' => [ 'uri' => 'https://twitter.com/intent/tweet', 'titleName' => 'text', 'mediaName' => 'media' ]
'twitter' => [ 'uri' => 'https://twitter.com/intent/tweet', 'titleName' => 'text', 'mediaName' => 'media_id' ]
'twitter' => [ 'uri' => 'https://twitter.com/intent/tweet', 'titleName' => 'text', 'mediaName' => 'picture' ]

But nothing works.

Thank you!

**Comment by datashaman** [comment]
You should annotate your page according to these links and Twitter will automatically attach an image when your URL is shared.

https://dev.twitter.com/cards/overview
https://cards-dev.twitter.com/validator
http://stackoverflow.com/questions/17825195/twitter-share-button-but-with-image
