### ISSUE TITLE
How do you make it work in a controller?

### ISSUE THREAD

**Issue by Jimmylet** [prodeveloper/social-share#24]
Hello,

I start in Laravel and I try to make social-share work. But impossible to get there.

I always have the error `Non-static method Chencha\Share\Share::load() should not be called statically`

Here's what I do in my controller 

```php
public function share()
    {
        $test = Share::load(url('/'), 'Description de test')->twitter();
        return $test;
    }
```

In my controller show

```php
return view('posts.postWork', [
            'work' => $work,
            'share' => $this->share()
        ]);
```

**Comment by datashaman** [comment]
Show me the whole file, please.

**Comment by Tjoosten** [comment]
just add `use Share` and everything works.
