### ISSUE TITLE
How to add description and thumbnail image on facebook share.

### ISSUE THREAD

**Issue by kevinreytabada** [prodeveloper/social-share#25]
Hi, How can i add description and thumbnail image on facebook share? i've notice only title and link can only add to the parameter. waiting for u reply. Thank You.

**Comment by Tjoosten** [comment]
Use the openGraph Tags from facebook.

**Comment by datashaman** [comment]
https://developers.facebook.com/docs/sharing/opengraph/using-objects#objectapi
