### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jaygagnani** [prodeveloper/social-share#26]
Facebook share is not working.
and google share does not takes the link. It just shows the share page with no pre-added content (the url we want to share)

**Comment by Tjoosten** [comment]
Have u tried the social meta tags?

**Comment by datashaman** [comment]
I need more info than: It's not working. I have created a test project to see if this is the case, and both `facebook` and `gplus` sharing works exactly as expected, using example.com:

```
Route::get('/', function () {
    return redirect()->to(Share::load('http://www.example.com', 'My example')->gplus());
});
```

This was with current Laravel 5.4. Re-open if you have more info, please.
