### ISSUE TITLE
Download via composer doesn't work

### ISSUE THREAD

**Issue by tamerkalieh** [prodeveloper/social-share#27]
Hey, 

if I do : composer require chencha/share it says that my composer.json gets updated and the package is downloaded. After adding : 

        Chencha\Share\ShareServiceProvider::class,
and Alias: 
        'Share' => Chencha\Share\ShareFacade::class,

I only get the error with the service provider: 

 (1/1) FatalErrorException
Class 'Chencha\Share\ShareServiceProvider' not found

Do you know something about that? I also tried a dump-autolaod after process but that haven't solved the problem. I would manually download the files but I don't know where I need to put all the files.. 
The config file in the config folder, the views in the views of course but where shall I put the Chencha/Share files?

**Comment by datashaman** [comment]
No idea, I'm afraid. I've just created a test project using the instructions given and it works perfectly. Try doing the following command to see that composer has correctly setup the autoload paths:

```
grep -R Chencha vendor/composer 
vendor/composer/installed.json:                "Chencha\\Share": "src/"
vendor/composer/autoload_namespaces.php:    'Chencha\\Share' => array($vendorDir . '/chencha/share/src'),
vendor/composer/autoload_static.php:            'Chencha\\Share' => 
vendor/composer/autoload_static.php:        'Chencha\\Share\\Share' => __DIR__ . '/..' . '/chencha/share/src/Chencha/Share/Share.php',
vendor/composer/autoload_static.php:        'Chencha\\Share\\ShareFacade' => __DIR__ . '/..' . '/chencha/share/src/Chencha/Share/ShareFacade.php',
vendor/composer/autoload_static.php:        'Chencha\\Share\\ShareServiceProvider' => __DIR__ . '/..' . '/chencha/share/src/Chencha/Share/ShareServiceProvider.php',
vendor/composer/autoload_classmap.php:    'Chencha\\Share\\Share' => $vendorDir . '/chencha/share/src/Chencha/Share/Share.php',
vendor/composer/autoload_classmap.php:    'Chencha\\Share\\ShareFacade' => $vendorDir . '/chencha/share/src/Chencha/Share/ShareFacade.php',
vendor/composer/autoload_classmap.php:    'Chencha\\Share\\ShareServiceProvider' => $vendorDir . '/chencha/share/src/Chencha/Share/ShareServiceProvider.php',
```

**Comment by datashaman** [comment]
If those aren't there then it's something wrong with your OS and composer.
