### ISSUE TITLE
How to pass media url for Pinterest?

### ISSUE THREAD

**Issue by od3n** [prodeveloper/social-share#28]

**Comment by cyrildewit** [comment]
I think as a third argument?

Something like: `Share::load('http://www.example.com', 'My example', 'http://www.example.com/img/social/image.jpg')->pinterest()`

**Comment by datashaman** [comment]
Correct! The third argument `media` becomes the `media` argument in the sharing URL for _pinterest_.

**Comment by od3n** [comment]
thank you
