### ISSUE TITLE
Call to undefined function Chencha\Share\array_get()

### ISSUE THREAD

**Issue by goran-popovic** [prodeveloper/social-share#38]
It seems that composer hasn't updated the package to your latest commit which resolves the issue with Laravel 6. 

This seems to elaborate the issue: https://stackoverflow.com/questions/22608398/composer-update-not-pulling-latest-dev-master

Hoping for a quick update, since I would really like to use your package.

Best regards.

**Comment by alphamarket** [comment]
I'm having this issue as well, but when I try to switch to the `dev-master` in my `composer.json` I am getting the following exception.

![image](https://user-images.githubusercontent.com/2348936/71573093-5a63cc80-2af7-11ea-888d-0b6266ebfca1.png)

BUT when I am using the `v5.4` version (the latest version) I am getting the following
![image](https://user-images.githubusercontent.com/2348936/71573121-83845d00-2af7-11ea-9434-92508a4baa37.png)

**Comment by datashaman** [comment]
The guy who owns the npm pkg is AWOL. This has been fixed in master. Follow instructions here to install master copy: https://github.com/prodeveloper/social-share/issues/36
