### ISSUE TITLE
Non-static method Chencha\Share\Share::load() should not be called statically

### ISSUE THREAD

**Issue by PR4M** [prodeveloper/social-share#40]
Hello, 

When I'm using this library, I got this error:
Non-static method Chencha\Share\Share::load() should not be called statically

My code:
```php
$socials = Share::load(route('post.show', [$post]), $post->tagline)
                    ->services('facebook', 'linkedin', 'telegram', 'twitter', 'email');

dd($socials); exit;
```

I'm using Laravel 6.4 

Thanks

**Comment by datashaman** [comment]
Use either: `Share` if you have the alias defined or `Chencha\Share\ShareFacade` if you don't.
