### ISSUE TITLE
The 5.4.1 tag is not accessible trough packagist.org / composer

### ISSUE THREAD

**Issue by reppair** [prodeveloper/social-share#43]
According to the [packagist.org](https://packagist.org/packages/chencha/share) the latest version of the package is `5.4.0`.

However here in GitHub you have the [5.4.1](https://github.com/prodeveloper/social-share/releases/tag/5.4.1) version.

So `composer require` / `composer install` results in:
```
- Installing chencha/share (5.4.0): Downloading (100%)
```

And as you are well aware (I assume) without the (`5.4.1`) fix for the `array_get()` helper, the package is not really usable in Laravel `6.x`.. 

Maybe the the webhook to sync with packagist.org got removed or something like this? Is it possible for you to check it or manually sync it with packagist?

Thanks, Martin

**Comment by datashaman** [comment]
Hi there, sadly the owner of this repo has gone AWOL and is not answering requests for assistance with the _npm_ entry. 

Try something like this: https://github.com/prodeveloper/social-share/issues/36#issuecomment-532639167

Or you might be able to use `prodeveloper/social-share:dev-master` as a package - that should go to GitHub for the source.

**Comment by reppair** [comment]
Yeah, thanks for the advice. Hope this gets resolved soon.

**Comment by datashaman** [comment]
The latest release is available on packagist.
