### ISSUE TITLE
The package is not auto updated on packagist.org

### ISSUE THREAD

**Issue by ahmeddabak** [prodeveloper/social-share#46]
The latest version available on packagist.org is 5.4, which works only with < laravel 7.x.

There is also a red message on the bottom right corner "This package is not auto-updated."

**Comment by wsenjer** [comment]
I have the same issue, please release the 5.5 tag to packagist.org. 
Thanks for the nice package.

**Comment by datashaman** [comment]
The latest release is available on packagist. Thanks for your patience.
