### ISSUE TITLE
This package in not installing in laravel 7

### ISSUE THREAD

**Issue by webartisanamit** [prodeveloper/social-share#47]
Problem 1
    - Installation request for chencha/share ^5.4 -> satisfiable by chencha/share[5.4.0].
    - Conclusion: remove laravel/framework v7.16.1
    - Conclusion: don't install laravel/framework v7.16.1
    - chencha/share 5.4.0 requires illuminate/support ^5.0|^6.0

Please update it for laravel new version.

**Comment by lsmith77** [comment]
see https://github.com/prodeveloper/social-share/issues/52

**Comment by datashaman** [comment]
This is resolved in the latest release, which is also available on packagist.
