### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by yousefyahya** [prodeveloper/social-share#57]

**Comment by arbabi2010** [comment]
Hi. I get this error for laravel 8.15.0

  Problem 1
    - Root composer.json requires chencha/share ^5.4 -> satisfiable by chencha/share[5.4.0].
    - chencha/share 5.4.0 requires illuminate/support ^5.0|^6.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but these were not loaded, likely because it
conflicts with another require.

**Comment by Omar-Abdelrady** [comment]
same error
