### ISSUE TITLE
Issue in default.blade.php on Laravel 6

### ISSUE THREAD

**Issue by paishin** [prodeveloper/social-share#59]
I have been using this plugin for quite some time on Laravel 5, I have decided to move project to Laravel 6 and upgraded Chencha/Share plugin to 5.4. I am now getting the following issue
_"Undefined index: uri (View: /home/vagrant/Code/vendor/chencha/share/src/views/default.blade.php):line1"_

Looking at default.blade.php I can see that the issue is the first {{$service['uri'] }}, silencing that out  makes everything working fine again:
`{{ **@$service['uri']** }}?{{ isset($service['urlName']) ? $service['urlName'] : 'url' }}={{ rawurlencode($url) }}<?php if(isset($title) && !empty($title)) { ?><?php echo $sep; ?>{{ isset($service['titleName']) ? $service['titleName'] : 'title' }}={{ rawurlencode($title) }}<?php } ?><?php if(isset($service['mediaName']) && !empty($media)) { ?><?php echo $sep; ?>{{ $service['mediaName'] }}={{ rawurlencode($media) }}<?php } ?><?php if (!empty($service['extra'])) { ?><?php echo $sep; ?><?php echo http_build_query($service['extra'], null, $sep, PHP_QUERY_RFC3986) ?><?php } ?>`

Why do I get this error? Am I missing something or is this an issue with the package?

**Comment by paishin** [comment]
Coming back to this, it turns out that silencing the $service['uri'] does not actually fix the problem as now the proper urls are not generated.

**Comment by paishin** [comment]
The problem is resolved by publishing provider files that was not required in previous version of the plugin.
I believe that the documentation needs to be updated if this is a requirement.

**Comment by datashaman** [comment]
The README was updated 6 years ago with instructions to publish vendor files.
https://github.com/prodeveloper/social-share/commit/ae7f7bf6ca20e08bdba78eda4734da52b856e604
