### ISSUE TITLE
Missing argument 1 for Chencha\Share\Share::__construct()

### ISSUE THREAD

**Issue by javiermar** [prodeveloper/social-share#6]
I started getting an error for the missing argument for
public function __construct($app){
        $this->app = $app;
    }

What is the $app param supposed to be?

**Comment by datashaman** [comment]
This package is for use with Laravel. You should use it as described in the README (and in the tests).

Add the Share facade to config/app.php, and use it.

You're trying to create the Chencha\Share\Share class directly, instead of using the Share facade (Chencha\Share\ShareFacade).

PS: $app is the Laravel app, if you want to see the Share class being created, look in the Chencha\Share\ShareServiceProvider class.

**Comment by datashaman** [comment]
As an aside, are you wanting to try use this outside of Laravel? I could get the package to support that. It currently uses Laravel for other things like templating, config (and possibly translation), but I could make a plan to separate those parts out, so it can be used with or without Laravel.

**Comment by javiermar** [comment]
Hi. I see what you mean about the service provider passing the $app param. So I'm trying to do it the way you describe, using the facade. Here's what I have:

config/app.php

// Added to providers array
Chencha\Share\ShareServiceProvider, 
// Should it be Chencha\Share\ShareServiceProvider::class,?

// Added to aliases array
'Share'     => Chencha\Share\ShareFacade,
// Should it be 'Share'     => Chencha\Share\ShareFacade::class,

I'm using laravel 5

If I try to use the face, I get the following error:
// I'm using it inside a model, so $this->title and $this->slug are present
$this->social = Share::load('http://domain.com/'. $this->slug, $this->title, $this->title )->services();

Non-static method Chencha\Share\Share::load() should not be called statically, assuming $this from incompatible context

Thank you for your reply, I appreciate it.

**Comment by datashaman** [comment]
You're again using the wrong class. Do not _use Chencha\Share\Share_ directly. Adding an alias to config/app.php adds a global class called Share. Try _use Share_ instead.

**Comment by javiermar** [comment]
I don't see how I'm using the Chencha\Share\Share class directly.
I've added the alias and registered the service provider, the class doesn't seem get registered. 

Thank you for your help, I've written the share urls into the model directly.

**Comment by scvishnu7** [comment]
If you are using PHPStrom, It is not auto importing the alias. I don't know why but It imports the Class from original package instead from the alias.
I faced the same problem and it gets resolved when I changed the 'use Chencha\Share\Share' to 'use Share'. Doing this uses the alias we wrote on app.php. And things will work.

**Comment by datashaman** [comment]
This might help you, @scvishnu7 https://github.com/barryvdh/laravel-ide-helper
