### ISSUE TITLE
mailto example in docs misses :

### ISSUE THREAD

**Issue by KHucks** [prodeveloper/social-share#7]
The mailto example on this page misses a ":" and should also have rawurlencode instead of urlencode

mailto?subject={{ urlencode("Wow, check this: $title") }}<?php echo $sep; ?>body={{ urlencode("Check this out! $title. See it here: $url") }}

Like this:
mailto:?subject={{ rawurlencode("Wow, check this: $title") }}<?php echo $sep; ?>body={{ rawurlencode("Check this out! $title. See it here: $url") }}

With missing ":" it does not work and the rawurlencode removed the ugly "+" symbolds in text.

**Comment by datashaman** [comment]
Thanks (well spotted), incorporated changes into a new hotfix release: 5.2.1
