### ISSUE TITLE
The thumbnail image is not displayed

### ISSUE THREAD

**Issue by JibrilYasin** [prodeveloper/social-share#9]
Hi @datashaman ,, Sorry

I have a little problem when sharing to facebook. Image thumbnails are not appearing. Any suggestions for me?

Thanks

**Comment by datashaman** [comment]
Hi,

Use the Facebook Debugger to figure out what you should do.

https://developers.facebook.com/tools/debug/

Typically you add something like this to your shared page:

<meta property="og:image" content="http://mydomain/somepath/image.png" />

This hints to Facebook which image to use (they could still choose
something else based on the page's HTML).

M.
